### ISSUE TITLE
ASMARA says recently issued alert is very expired

### ISSUE THREAD

**Issue by miceoroni** [A-c0rN/ASMARA#37] opened 2024-03-03 11:41 UTC
whenever any alert gets passed through the script, it says the alert is **very** expired. could anyone look into this and provide a solution? thanks! here is a log file to what I'm experiencing: 
[logthing.txt](https://github.com/A-c0rN/ASMARA/files/14472737/logthing.txt)

**Comment by reggietorres** [comment] 2024-03-03 15:16
Your alert needs to be from today's date, it won't send it if the alert has passed its expire time @miceoroni

**Comment by miceoroni** [comment] 2024-03-03 17:41
my brain can't really comprehend 24-hour time 💀 thanks!

**Comment by TamShep** [comment] 2024-03-05 16:26
Due to it being a leap year, the program isn't able to calculate the "Very Expired" as well as "Too Early" values for some reason.

This is a genuine issue and it is an issue with the way the program calculates the time and date.

**Comment by reggietorres** [comment] 2024-03-05 17:10
same here, i'm able to reproduce

**Comment by physprop** [comment] 2024-03-06 18:48
It doesn't help that those start/end timestamps are from the future.

Keep in mind that epoch does not include leap seconds.

@A-c0rN should take a look at this.

**Comment by A-c0rN** [comment] 2024-03-10 03:58
The code is designed to throw out alerts if it's greater than ~5 hours in the future, assuming that the alert was sent over a year ago.
This kinda failed because it assumed the alert was 1 day in advance. This isn't necessarily an issue with ASMARA, but the underlying libraries I use.

I'll look into workarounds, this issue has bit me in the ass too many times now lmao

**Comment by ManMacho** [comment] 2024-03-11 01:15
Im having this issue too :/

**Comment by ShowLowfinityHarvester** [comment] 2024-03-14 00:09
me three

**Comment by ManMacho** [comment] 2024-03-26 17:39
@A-c0rN I have found a fix to this, I'd love to share it with you through discord or something, if needed.

**Comment by reggietorres** [comment] 2024-03-26 19:08
> @A-c0rN I have found a fix to this, I'd love to share it with you through discord or something, if needed.

If you have code, fork the project and send a pull request

If you don't but have an idea on how, write a three page essay on how (lol, just tell us how, include line numbers)

**Comment by A-c0rN** [comment] 2024-06-05 04:09
> There is a hot fix on my github

Lol removing the code isn't a fix, it's covering up the underlying issue.

Sorry I haven't been available, It's that time of year.
Just started getting back into the project, and there's gonna be a massive code refactor coming. 

and this one will be fun :3

**Comment by reggietorres** [comment] 2024-06-06 02:54
> > There is a hot fix on my github
> 
> Lol removing the code isn't a fix, it's covering up the underlying issue.

Yeah thats what I told him

**Comment by physprop** [comment] 2024-06-26 09:11
I have this properly fixed in my personal repository. Made a pull request so we can merge it to the mainline.

**Comment by reggietorres** [comment] 2024-06-26 15:54
> I have this properly fixed in my personal repository. Made a pull request so we can merge it to the mainline.

Awesome, il take a look at it when I have time.

**Closed** 2024-06-26 21:43 UTC
Labels: bug
